version: '3.1'

services:
  api:
    image: docker.studyum.net/api
    restart: always
    # noinspection ComposeUnknownKeys
    pull_policy: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:433"
