// Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplatejournal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "responses": {}
            }
        },
        "/absences": {
            "put": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/absences/list": {
            "post": {
                "responses": {}
            }
        },
        "/absences/{id}": {
            "delete": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Absence ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/generate/absences": {
            "post": {
                "responses": {}
            }
        },
        "/generate/marks": {
            "post": {
                "responses": {}
            }
        },
        "/mark": {
            "put": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/mark/list": {
            "post": {
                "responses": {}
            }
        },
        "/mark/{id}": {
            "delete": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mark ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/options": {
            "get": {
                "responses": {}
            }
        },
        "/{group}/{subject}/{teacher}": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subject",
                        "name": "subject",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Teacher",
                        "name": "teacher",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfojournal holds exported Swagger Info so clients can modify it
var SwaggerInfojournal = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/journal",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "journal",
	SwaggerTemplate:  docTemplatejournal,
}

func init() {
	swag.Register(SwaggerInfojournal.InstanceName(), SwaggerInfojournal)
}
