// Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplateauth = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/email/confirm": {
            "post": {
                "responses": {}
            }
        },
        "/email/resendCode": {
            "post": {
                "responses": {}
            }
        },
        "/login": {
            "put": {
                "responses": {}
            }
        },
        "/oauth2/callback/{service}": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth2 Server",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/oauth2/{service}": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth2 Server",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/sessions": {
            "delete": {
                "responses": {}
            }
        },
        "/signout": {
            "delete": {
                "responses": {}
            }
        },
        "/signup": {
            "post": {
                "responses": {}
            }
        },
        "/signup/code": {
            "post": {
                "responses": {}
            }
        },
        "/signup/stage1": {
            "put": {
                "responses": {}
            }
        },
        "/token": {
            "post": {
                "responses": {}
            }
        }
    }
}`

// SwaggerInfoauth holds exported Swagger Info so clients can modify it
var SwaggerInfoauth = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/user",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "auth",
	SwaggerTemplate:  docTemplateauth,
}

func init() {
	swag.Register(SwaggerInfoauth.InstanceName(), SwaggerInfoauth)
}
