name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  IMAGE_NAME: "studyum-api"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy to Aeza
        uses: appleboy/ssh-action@v0.1.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

          envs: GITHUB_REPOSITORY, IMAGE_NAME

          script: |
            rm -r ${GITHUB_REPOSITORY#*/}
            git clone git@github.com:${{ github.repository }}.git
            cd ${GITHUB_REPOSITORY#*/}
            docker rmi ${IMAGE_NAME}
            docker build -t ${IMAGE_NAME} .
            docker stop ${IMAGE_NAME}
            docker rm ${IMAGE_NAME}
            docker run \
            -d -p 274:8080 \
            -e DB_URL='${{ secrets.DB_URL }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            -e GOOGLE_SECRET='${{ secrets.GOOGLE_SECRET }}' \
            -e GIN_MODE='release' \
            -e OAUTH2_CALLBACK='https://studyum.net' \
            --restart always \
            --name ${IMAGE_NAME} \
            ${IMAGE_NAME}
            docker rmi $(docker images -f "dangling=true" -q)

