name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            git clone git@github.com:${{ github.repository }}.git
            cd ${GITHUB_REPOSITORY#*/}
            docker build -t ${GITHUB_REPOSITORY#*/} . 
            docker run \
            -d -p 274:8080 \
            -e DB_URL='${{ secrets.DB_URL }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            -e GOOGLE_SECRET='${{ secrets.GOOGLE_SECRET }}' \
            -e GIN_MODE='release' \
            -e OAUTH2_CALLBACK='https://studyum.net' \
            --restart always \
            --name ${GITHUB_REPOSITORY#*/} \
            ${GITHUB_REPOSITORY#*/}

