name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean droplet via SSH action
#        uses: appleboy/ssh-action@v0.1.3
        run: |
          echo git clone git@github.com:${{ github.repository }}.git


