name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rm -r $(echo ${GITHUB_REPOSITORY#*/})


