name: Build and Push Image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  sync:
    name: Syncing Files
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SyncGrpc and Docker Compose
        uses: LikDan/SyncRepositoriesAction@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: 'Syncing'
          email: 'likdan.official@gmail.com'
      - uses: actions/checkout@v2
